### ISSUE TITLE
BeagleBone Code with Python3

### ISSUE THREAD

**Issue by phpfs** [SparkysWidgets/MinipHBFW#3]
Hello!     

When I try to use your awesome Code with Python3, i get this error:     

``` shell
user@host.domain:~$ python3 pHReader.py          
Traceback (most recent call last):     
  File "pHReader.py", line 69, in <module>          
    main()     
  File "pHReader.py", line 60, in main     
    phr = pHReader()     
  File "pHReader.py", line 33, in __init__     
    self.params = pHParams.pHParams()     
  File "/home/user/pHParams.py", line 31, in __init__     
    self.slope, self.intercept = self.calc_ph_slope()     
  File "/home/user/pHParams.py", line 97, in calc_ph_slope     
    slope, intercept, r_value, p_value, std_err = scipy.linregress(x, y)     
  File "/usr/lib/python3/dist-packages/scipy/stats/stats.py", line 3008, in linregress     
    ymean = np.mean(y,None)     
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2716, in mean     
    out=out, keepdims=keepdims)     
  File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 69, in _mean     
    ret = ret / rcount     
TypeError: unsupported operand type(s) for /: 'dict_values' and 'int'     
```

Do you have any idea what happened here?  
(By the way: I fixed all common Python2->3 Bugs myself, but got stuck here 😔)     

Greetings phpfs

**Comment by phpfs** [comment]
Maybe related to Scipy/Numpy?! 
I also opened an issue there 😀

Update: Bug not related to Numpy, wrong values send to linregress!

**Comment by phpfs** [comment]
Hello :)

I fixed it:
{MinipHBFW/BeagleBone/pHParams.py}

``` python
    def calc_ph_slope(self):
        """Based on the calibration readings, a line of best fit is calulated.
        This line will be used to calculate the pH step i.e. millivolts to
        pH value.
        """
        #x = [float(x) for x in self.calibs.keys()]
        #y = self.calibs.values() --> Values aren't numbers, they are dict-parts
        #slope, intercept, r_value, p_value, std_err = scipy.linregress(x, y)

        xy = [ [float(x), float(y)] for x, y in self.calibs.items() ]
        #Key and Value get converted in float(), then put in 2d list
        slope, intercept, r_value, p_value, std_err = scipy.linregress(xy)
```

I hope that will help someone else too!

Greetings, phpfs
